defmodule Common.Api.PackageInfo do
  @derive Jason.Encoder
  defstruct [
    :first_name,
    :last_name,
    :actual_weight,
    :estimated_weight,
    :length,
    :width,
    :height,
    :insured,
    :package_number,
    :delivery_method,
    :saturday_delivery,
    :sunday_delivery,
    :po_box,
    :residential,
    :hazmat,
    :ship_date,
    :shipper_id,
    :loc_type,
    :time_zone,
    :expected_delivery_date,
    :packages_scanned,
    :total_packages,
    :division,
    :loc,
    :is_package_override,
    :shipper_reference,
    :consignee_reference,
    :package_total_cost,
    :dimension_required,
    :department
  ]
end
